(cl:defpackage rover-srv
  (:use )
  (:export
   "TOGGLEIMUREPRESENTATION"
   "<TOGGLEIMUREPRESENTATION-REQUEST>"
   "TOGGLEIMUREPRESENTATION-REQUEST"
   "<TOGGLEIMUREPRESENTATION-RESPONSE>"
   "TOGGLEIMUREPRESENTATION-RESPONSE"
  ))

