ekf_localization_node:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  imu0: /imu/data_raw
  imu0_config:
    transform_time_offset: 0.0
    transform_timeout: 0.0
    queue_size: 10
    linear_acceleration:
      x: 0.0
      y: 0.0
      z: 0.0
    angular_velocity:
      x: 0.0
      y: 0.0
      z: 0.0

  odom0: /odom
  odom0_config:
    transform_time_offset: 0.0
    transform_timeout: 0.0
    queue_size: 10
    pose_rejection_threshold: 5.0
    twist_rejection_threshold: 1.0

