// Generated by gencpp from file rover/ToggleIMURepresentation.msg
// DO NOT EDIT!


#ifndef ROVER_MESSAGE_TOGGLEIMUREPRESENTATION_H
#define ROVER_MESSAGE_TOGGLEIMUREPRESENTATION_H

#include <ros/service_traits.h>


#include <rover/ToggleIMURepresentationRequest.h>
#include <rover/ToggleIMURepresentationResponse.h>


namespace rover
{

struct ToggleIMURepresentation
{

typedef ToggleIMURepresentationRequest Request;
typedef ToggleIMURepresentationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleIMURepresentation
} // namespace rover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rover::ToggleIMURepresentation > {
  static const char* value()
  {
    return "52512739d54d35724c9fe339cf727a07";
  }

  static const char* value(const ::rover::ToggleIMURepresentation&) { return value(); }
};

template<>
struct DataType< ::rover::ToggleIMURepresentation > {
  static const char* value()
  {
    return "rover/ToggleIMURepresentation";
  }

  static const char* value(const ::rover::ToggleIMURepresentation&) { return value(); }
};


// service_traits::MD5Sum< ::rover::ToggleIMURepresentationRequest> should match
// service_traits::MD5Sum< ::rover::ToggleIMURepresentation >
template<>
struct MD5Sum< ::rover::ToggleIMURepresentationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rover::ToggleIMURepresentation >::value();
  }
  static const char* value(const ::rover::ToggleIMURepresentationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover::ToggleIMURepresentationRequest> should match
// service_traits::DataType< ::rover::ToggleIMURepresentation >
template<>
struct DataType< ::rover::ToggleIMURepresentationRequest>
{
  static const char* value()
  {
    return DataType< ::rover::ToggleIMURepresentation >::value();
  }
  static const char* value(const ::rover::ToggleIMURepresentationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rover::ToggleIMURepresentationResponse> should match
// service_traits::MD5Sum< ::rover::ToggleIMURepresentation >
template<>
struct MD5Sum< ::rover::ToggleIMURepresentationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rover::ToggleIMURepresentation >::value();
  }
  static const char* value(const ::rover::ToggleIMURepresentationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover::ToggleIMURepresentationResponse> should match
// service_traits::DataType< ::rover::ToggleIMURepresentation >
template<>
struct DataType< ::rover::ToggleIMURepresentationResponse>
{
  static const char* value()
  {
    return DataType< ::rover::ToggleIMURepresentation >::value();
  }
  static const char* value(const ::rover::ToggleIMURepresentationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVER_MESSAGE_TOGGLEIMUREPRESENTATION_H
